// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "github.com/lantosgyuri/auction-portal/internal/command-service/domain"

import mock "github.com/stretchr/testify/mock"

// AuctionEventPreserver is an autogenerated mock type for the AuctionEventPreserver type
type AuctionEventPreserver struct {
	mock.Mock
}

// Handle provides a mock function with given fields: eventName, event
func (_m *AuctionEventPreserver) Handle(eventName string, event domain.AuctionEvent) error {
	ret := _m.Called(eventName, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.AuctionEvent) error); ok {
		r0 = rf(eventName, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
