// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "github.com/lantosgyuri/auction-portal/internal/command-service/domain"

import mock "github.com/stretchr/testify/mock"

// AuctionCreateEventHandler is an autogenerated mock type for the AuctionCreateEventHandler type
type AuctionCreateEventHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: event
func (_m *AuctionCreateEventHandler) Handle(event domain.CreateAuctionRequested) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.CreateAuctionRequested) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
