// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import domain "github.com/lantosgyuri/auction-portal/internal/command-service/domain"

import mock "github.com/stretchr/testify/mock"

// BidPLacedEventHandler is an autogenerated mock type for the BidPLacedEventHandler type
type BidPLacedEventHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, placed
func (_m *BidPLacedEventHandler) Handle(ctx context.Context, placed domain.BidPlaced) error {
	ret := _m.Called(ctx, placed)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BidPlaced) error); ok {
		r0 = rf(ctx, placed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
