// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import domain "github.com/lantosgyuri/auction-portal/internal/command-service/domain"

import mock "github.com/stretchr/testify/mock"

// UserDeleteEventHandler is an autogenerated mock type for the UserDeleteEventHandler type
type UserDeleteEventHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, event
func (_m *UserDeleteEventHandler) Handle(ctx context.Context, event domain.DeleteUserRequest) error {
	ret := _m.Called(ctx, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.DeleteUserRequest) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
