// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "github.com/lantosgyuri/auction-portal/internal/command-service/domain"

import mock "github.com/stretchr/testify/mock"

// UserNotifier is an autogenerated mock type for the UserNotifier type
type UserNotifier struct {
	mock.Mock
}

// NotifyUserFail provides a mock function with given fields: notifyEvent
func (_m *UserNotifier) NotifyUserFail(notifyEvent domain.NotifyEvent) {
	_m.Called(notifyEvent)
}

// NotifyUserSuccess provides a mock function with given fields: notifyEvent
func (_m *UserNotifier) NotifyUserSuccess(notifyEvent domain.NotifyEvent) {
	_m.Called(notifyEvent)
}
