// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import domain "github.com/lantosgyuri/auction-portal/internal/command-service/domain"

import mock "github.com/stretchr/testify/mock"

// WinnerAnnouncedEventHandler is an autogenerated mock type for the WinnerAnnouncedEventHandler type
type WinnerAnnouncedEventHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0, event
func (_m *WinnerAnnouncedEventHandler) Handle(_a0 context.Context, event domain.WinnerAnnounced) error {
	ret := _m.Called(_a0, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.WinnerAnnounced) error); ok {
		r0 = rf(_a0, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
