// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import domain "github.com/lantosgyuri/auction-portal/internal/command-service/domain"
import mock "github.com/stretchr/testify/mock"

// StateRepository is an autogenerated mock type for the StateRepository type
type StateRepository struct {
	mock.Mock
}

// UpdateState provides a mock function with given fields: _a0, event, update
func (_m *StateRepository) UpdateState(_a0 context.Context, event domain.AuctionEvent, update func(domain.Auction) (domain.Auction, error)) error {
	ret := _m.Called(_a0, event, update)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuctionEvent, func(domain.Auction) (domain.Auction, error)) error); ok {
		r0 = rf(_a0, event, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
